package shared;


/**
* shared/ServerInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IDL.idl
* Tuesday, October 20, 2020 9:19:02 o'clock PM EDT
*/

public interface ServerInterfaceOperations 
{
  String ReturnItem (String customerId, String itemId, String dateOfReturn);
  String PurchaseItem (String customerId, String itemId, String dateOfPurchase);
  String[] FindItem (String customerId, String itemDescription);
  String AddCustomerToWaitList (String itemId, String customerId);
  String AddItem (String managerId, String itemId, String itemName, int quantity, double price);
  String RemoveItem (String managerId, String itemId, int quantity);
  String[] ListItemAvailability (String managerId);
  String exchangeItem (String customerId, String newItemId, String oldItemId, String dateOfReturn);
  void shutdown ();
} // interface ServerInterfaceOperations
