package shared;


/**
* shared/ServerInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IDL.idl
* Tuesday, October 20, 2020 9:19:02 o'clock PM EDT
*/

public interface ServerInterface extends ServerInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ServerInterface
