module shared {

	interface ServerInterface  {
	
		typedef sequence<string> products; 
	
		string ReturnItem (in string customerId, in string itemId, in string dateOfReturn);
		string PurchaseItem(in string customerId, in string itemId, in string dateOfPurchase);
		products FindItem(in string customerId, in string itemDescription);
		string AddCustomerToWaitList(in string itemId, in string customerId);
		string AddItem(in string managerId, in string itemId, in string itemName, in long quantity, in double price);
		string RemoveItem(in string managerId, in string itemId, in long quantity);
		products ListItemAvailability(in string managerId);
		string exchangeItem (in string customerId, in string newItemId, in string oldItemId, in string dateOfReturn);
		oneway void shutdown();
	};
};