package StoreMod;


/**
* StoreMod/ArrayHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/SOEN/SOEN423/Assignment2/build/classes/Store.idl
* Thursday, October 15, 2020 4:01:34 o'clock PM EDT
*/

public final class ArrayHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public ArrayHolder ()
  {
  }

  public ArrayHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = StoreMod.ArrayHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    StoreMod.ArrayHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return StoreMod.ArrayHelper.type ();
  }

}
