package StoreMod;


/**
* StoreMod/StoreOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/SOEN/SOEN423/Assignment2/build/classes/Store.idl
* Thursday, October 15, 2020 4:01:35 o'clock PM EDT
*/

public interface StoreOperations 
{
  String addItem (String managerID, String itemID, String itemName, int quantity, double price);
  String removeItem (String managerID, String itemID, int quantity);
  String[] listItemAvailability (String managerID);
  String purchaseItem (String customerID, String itemID, String dateOfPurchase);
  String[] findItem (String customerID, String itemName);
  String returnItem (String customerID, String itemID, String dateOfReturn);
  String exchangeItem (String customerID, String newItemID, String oldItemID, String dateOfExchange);
  void shutdown ();
} // interface StoreOperations
