package StoreMod;


/**
* StoreMod/Store.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/SOEN/SOEN423/Assignment2/build/classes/Store.idl
* Thursday, October 15, 2020 4:01:35 o'clock PM EDT
*/

public interface Store extends StoreOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Store
