package StoreMod;

/**
* StoreMod/StoreHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/SOEN/SOEN423/Assignment2/build/classes/Store.idl
* Thursday, October 15, 2020 4:01:35 o'clock PM EDT
*/

public final class StoreHolder implements org.omg.CORBA.portable.Streamable
{
  public StoreMod.Store value = null;

  public StoreHolder ()
  {
  }

  public StoreHolder (StoreMod.Store initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = StoreMod.StoreHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    StoreMod.StoreHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return StoreMod.StoreHelper.type ();
  }

}
